

USER_TEMPLATES: list[dict[str, str]] = [
    dict(
        name="sad linus",
        imgflip_name="sad linus",
        url="https://i.imgflip.com/3n7e0h.png",
        page="https://imgflip.com/meme/220374449/Sad-Linus?page={}",
    ),
    dict(
        name="confused unga bunga",
        imgflip_name="confused unga bunga",
        url="https://i.imgflip.com/38z8jt.jpg",
        page="https://imgflip.com/meme/196479497/Confused-Unga-Bunga?page={}",
    ),
]

DONT_USE_TEMPLATES = {"4 square grid",
                      "gasp rage face",
                      "baby crying",
                      "if you know what i mean bean",
                      "slenderman",
                      "brian williams was there 3",
                      "permission bane",
                      "tui",
                      "dancing trollmom",
                      "what my friends think i do",
                      "no soup for you",
                      "speechless colbert face",
                      "angry baby",
                      "valentines day card meme",
                      "blank colored background",
                      "blank comic panel 2x2",
                      "reverse kalm panik",
                      "does your dog bite",
                      "dumpster fire",
                      "wants to know your location",
                      "gangnam style",
                      "mom can we have",
                      "mr bean",
                      "smiling cat",
                      "noooo you cant just",
                      "be like bill",
                      "right in the childhood",
                      "braveheart",
                      "keep calm and carry on black",
                      "scumbag minecraft",
                      "they hated jesus meme",
                      "for dummies",
                      "george bush",
                      "bart simpson - chalkboard",
                      "business cat",
                      "surprised koala",
                      "two buttons 1 blue",
                      "urinal guy more text room",
                      "aw yeah rage face",
                      "bazooka squirrel",
                      "inspirational quote",
                      "joe biden",
                      "brian williams was there 2",
                      "fat asian kid",
                      "onde",
                      "why is the fbi here",
                      "eye of sauron",
                      "sonic says",
                      "jim lehrer the man",
                      "bart simpson peeking",
                      "cmon do something",
                      "y u no",
                      "lame pun coon",
                      "cnn breaking news template",
                      "shia labeouf just do it",
                      "you the real mvp 2",
                      "tech impaired duck",
                      "bonjour",
                      "hardworking guy",
                      "keep calm and carry on aqua",
                      "pepe the frog",
                      "hey internet",
                      "captain america so you",
                      "blank pokemon card",
                      "liam neeson taken",
                      "big book small book",
                      "internet explorer",
                      "computer guy",
                      "comic book guy",
                      "scumbag brain",
                      "blank comic panel 2x1",
                      "no take only throw",
                      "blank",
                      "farquaad pointing",
                      "sigmund freud",
                      "triggerpaul",
                      "extra-hell",
                      "blank for president",
                      "mario hammer smash",
                      "money man",
                      "there is 1 imposter among us",
                      "the most interesting cat in the world",
                      "wanted poster",
                      "computer horse",
                      "jersey santa",
                      "black background",
                      "silent movie card",
                      "2nd term obama",
                      "foul bachelor frog",
                      "i know that feel bro",
                      "scared cat",
                      "transparent",
                      "first world problems cat",
                      "meme man",
                      "jeopardy blank",
                      "unhappy baby",
                      "table flip guy",
                      "you made thisi made this",
                      "mexican word of the day",
                      "socially awkward awesome penguin",
                      "gravestone",
                      "challenge accepted rage face",
                      "blank transparent square",
                      "fist pump baby",
                      "blank black",
                      "awkward moment sealion",
                      "zuckerberg",
                      "original stoner dog",
                      "you underestimate my power",
                      "hohoho",
                      "angry birds pig",
                      "keep calm and carry on purple",
                      "arrogant rich man",
                      "no soup",
                      "facepalm bear",
                      "evil plotting raccoon",
                      "marked safe from",
                      "dolph ziggler sells",
                      "alarm clock",
                      "pepe silvia",
                      "nobody absolutely no one",
                      "honey its time to x",
                      "hold my beer",
                      "who would win",
                      "now thats what i call",
                      "gadsden flag",
                      "hipster ariel",
                      "keep calm and carry on red",
                      "hulk",
                      "confucius says",
                      "free",
                      "grumpy toad",
                      "laughing villains",
                      "blank blue background",
                      "stay alert",
                      "buddy the elf",
                      "brian williams was there",
                      "wtf",
                      "pokemon appears",
                      "cute cat",
                      "forever alone",
                      "team rocket",
                      "rod serling twilight zone",
                      "heavy breathing cat",
                      "warning sign",
                      "white background",
                      "blank white template",
                      "blank starter pack",
                      "metal jesus",
                      "blank t-shirt",
                      "iceberg",
                      "happy star congratulations",
                      "short satisfaction vs truth",
                      "serious xzibit",
                      "multi doge",
                      "malicious advice mallard",
                      "mr t pity the fool",
                      "banned from roblox",
                      "among us not the imposter",
                      "cereal guy",
                      "homophobic seal",
                      "neil degrasse tyson",
                      "nooo haha go brrr",
                      "you dont say",
                      "austin powers honestly",
                      "gotta go cat",
                      "impossibru guy original",
                      "blank comic panel 1x2",
                      "troll face",
                      "milk carton",
                      "yeet the child",
                      "blank yellow sign",
                      "take a seat cat",
                      "black screen",
                      "empty red and black"}


REPLICATED_TEMPLATES_GROUPED = {"no - yes": "drake noyes",
                                "rip headstone": "rip headstone",
                                "rip": "rip headstone",
                                "surprised pikachu high quality": "surprised pikachu",
                                "surprised pikachu": "surprised pikachu",
                                "stop it patrick! youre scaring him!": "stop it patrick! youre scaring him!",
                                "stop it  patrick! youre scaring him!": "stop it patrick! youre scaring him!",
                                "pretending to be happy hiding crying behind a mask": "pretending to be happy hiding crying behind a mask",
                                "pretending to be happy  hiding crying behind a mask": "pretending to be happy hiding crying behind a mask",
                                "pepperidge farms remembers": "pepperidge farms remembers",
                                "pepperidge farm remembers": "pepperidge farms remembers",
                                "patrick not my wallet": "patrick not my wallet",
                                "patrick star and man ray": "patrick not my wallet",
                                "oprah you get a": "oprah you get a",
                                "opera": "oprah you get a",
                                "oprah - you get a car": "oprah you get a",
                                "old lady at computer": "old lady at computer",
                                "old lady at computer finds the internet": "old lady at computer",
                                "okay guy rage face": "okay guy rage face",
                                "okay guy rage face 2": "okay guy rage face",
                                "maybe i am a monster": "maybe i am a monster",
                                "maybe i am a monster blank": "maybe i am a monster",
                                "obama medal": "obama medal",
                                "obama giving obama award": "obama medal",
                                "maury povich": "maury lie detector",
                                "vein forehead guy": "vein forehead guy",
                                "vein popping kid": "vein forehead guy",
                                "maury lie detector": "maury lie detector",
                                "i wish all the x a very pleasant evening": "i wish all x a very y",
                                "i wish all x a very y": "i wish all x a very y",
                                "here it comes": "here it comes",
                                "here it come meme": "here it comes",
                                "where banana": "where banana",
                                "where banana blank": "where banana",
                                "where monkey": "where banana",
                                "trust nobody  not even yourself": "trust nobody not even yourself",
                                "trust nobody not even yourself": "trust nobody not even yourself",
                                "ew  i stepped in shit": "ew i stepped in shit",
                                "ew i stepped in shit": "ew i stepped in shit",
                                "disloyal boyfriend": "distracted boyfriend",
                                "three dragons": "three dragons",
                                "three-headed dragon": "three dragons",
                                "tom and jerry": "tom the cat shooting himself",
                                "tom the cat shooting himself": "tom the cat shooting himself",
                                "distracted boyfriend": "distracted boyfriend",
                                "corporate needs you to find the differences": "corporate needs you to find the differences",
                                "corporate wants you to find the difference": "corporate needs you to find the differences",
                                "they are the same picture": "corporate needs you to find the differences",
                                "theyre the same picture": "corporate needs you to find the differences",
                                "chuckles  im in danger": "chuckles im in danger",
                                "chuckles im in danger": "chuckles im in danger",
                                "im in danger": "chuckles im in danger",
                                "captain america elevator": "captain america elevator fight",
                                "captain america elevator fight": "captain america elevator fight",
                                "average blank fan vs average blank enjoyer": "average fan vs average enjoyer",
                                "average fan vs average enjoyer": "average fan vs average enjoyer",
                                "anakin and padme": "anakin and padme",
                                "anakin padme 4 panel": "anakin and padme",
                                "all right then  keep your secrets": "all right then keep your secrets",
                                "all right then keep your secrets": "all right then keep your secrets",
                                "albert einstein 1": "albert einstein quotes",
                                "albert einstein quotes": "albert einstein quotes",
                                "drake blank": "drake noyes",
                                "drake meme": "drake noyes",
                                "drake yes no reverse": "drake noyes",
                                "drake hotline approves": "drake noyes",
                                "drake hotline bling": "drake noyes",
                                "drake noyes": "drake noyes",
                                "baby yoda die trash": "baby yoda",
                                "surprised baby yoda": "baby yoda",
                                "crying baby yoda": "baby yoda",
                                "sad baby yoda": "baby yoda",
                                "baby yoda tea": "baby yoda",
                                "baby yoda": "baby yoda",
                                "mr incredible mad": "math is math",
                                "math is math": "math is math",
                                "nemo birds": "nemo seagulls mine",
                                "nemo seagulls mine": "nemo seagulls mine",
                                "anime butterfly meme": "is this a pigeon",
                                "butterfly man": "is this a pigeon",
                                "is this a bird": "is this a pigeon",
                                "is this butterfly": "is this a pigeon",
                                "is this a pigeon": "is this a pigeon",
                                "is this a blank": "is this a pigeon",
                                "wait its all": "always has been",
                                "always has been": "always has been",
                                "admiral ackbar relationship expert": "admiral ackbar",
                                "its a trap": "admiral ackbar",
                                "admiral ackbar": "admiral ackbar",
                                "afraid to ask andy closeup": "afraid to ask andy",
                                "afraid to ask andy": "afraid to ask andy",
                                "all my homies hate": "all my homies",
                                "all my homies love": "all my homies",
                                "all my homies": "all my homies",
                                "aliens guy": "ancient aliens",
                                "ancient aliens": "ancient aliens",
                                "woman pointing at cat": "lady screams at cat",
                                "woman yelling at cat": "lady screams at cat",
                                "smudge the cat": "lady screams at cat",
                                "white cat table": "lady screams at cat",
                                "angry lady cat": "lady screams at cat",
                                "cat at table": "lady screams at cat",
                                "lady screams at cat": "lady screams at cat",
                                "astronaut meme always has been template": "always has been",
                                "batman slaps trump": "batman slapping robin",
                                "batman slapping robin": "batman slapping robin",
                                "bernie sanders mittens": "bernie mittens",
                                "bernie sitting": "bernie mittens",
                                "bernie mittens": "bernie mittens",
                                "i am once again asking": "bernie sanders once again asking",
                                "bernie i am once again asking for your support": "bernie sanders once again asking",
                                "bernie sanders once again asking": "bernie sanders once again asking",
                                "im about to end this mans whole career": "im about to end this mans whole career",
                                "jordan peele sweating": "sweating bullets",
                                "sweating bullets": "sweating bullets",
                                "hide the pain harold": "hide the pain harold",
                                "me and the boys": "me and the boys",
                                "monsters inc": "sully wazowski",
                                "sully wazowski": "sully wazowski",
                                "thinking black guy": "eddie murphy thinking",
                                "smart black guy": "eddie murphy thinking",
                                "you cant if you dont": "eddie murphy thinking",
                                "smart guy": "eddie murphy thinking",
                                "guy tapping head": "eddie murphy thinking",
                                "roll safe think about it": "eddie murphy thinking",
                                "black guy pointing at head": "eddie murphy thinking",
                                "black guy head tap": "eddie murphy thinking",
                                "eddie murphy thinking": "eddie murphy thinking",
                                "bender": "blackjack and hookers",
                                "blackjack and hookers": "blackjack and hookers",
                                "brace yourselves x is coming": "brace yourself",
                                "winter is coming": "brace yourself",
                                "brace yourself": "brace yourself",
                                "robotnik pressing red button": "two buttons",
                                "both buttons pressed": "two buttons",
                                "press button hard choice": "two buttons",
                                "two buttons": "two buttons",
                                "woody and buzz lightyear everywhere widescreen": "x x everywhere",
                                "x x everywhere": "x x everywhere",
                                "braveheart freedom": "braveheart",
                                "braveheart": "braveheart",
                                "black guy stopping": "bro not cool",
                                "bro not cool": "bro not cool",
                                "buddy the elf excited": "buddy the elf",
                                "buddy the elf": "buddy the elf",
                                "buff doge vs cheems": "buff doge vs crying cheems",
                                "big dog small dog": "buff doge vs crying cheems",
                                "strong dog vs weak dog": "buff doge vs crying cheems",
                                "buff doge vs crying cheems": "buff doge vs crying cheems",
                                "kermit sipping tea": "but thats none of my business",
                                "but thats none of my business neutral": "but thats none of my business",
                                "but thats none of my business": "but thats none of my business",
                                "car salesman slaps hood": "car salesman slaps roof of car",
                                "car salesman slaps roof of car": "car salesman slaps roof of car",
                                "car drift meme": "left exit 12 off ramp",
                                "car turning": "left exit 12 off ramp",
                                "left exit 12 off ramp": "left exit 12 off ramp",
                                "he will never get a girlfriend": "cereal guy",
                                "cereal guy spitting": "cereal guy",
                                "cereal guys daddy": "cereal guy",
                                "cereal guy": "cereal guy",
                                "change my mind crowder": "change my mind",
                                "prove me wrong": "change my mind",
                                "change my mind": "change my mind",
                                "charlie conspiracy always sunny in philidelphia": "charlie day",
                                "trying to explain": "charlie day",
                                "charlie day": "charlie day",
                                "chuck norris approves": "chuck norris",
                                "chuck norris finger": "chuck norris",
                                "chuck norris flex": "chuck norris",
                                "chuck norris guns": "chuck norris",
                                "chuck norris laughing": "chuck norris",
                                "chuck norris phone": "chuck norris",
                                "chuck norris with guns": "chuck norris",
                                "chuck norris": "chuck norris",
                                "cmon do something": "cmon do something",
                                "comic book guy worst ever": "comic book guy",
                                "comic book guy": "comic book guy",
                                "bugs bunny communist": "communist bugs bunny",
                                "our": "communist bugs bunny",
                                "communist bugs bunny": "communist bugs bunny",
                                "computer guy facepalm": "computer guy",
                                "computer horse": "computer guy",
                                "computer guy": "computer guy",
                                "adive yoda": "star wars yoda",
                                "star wars yoda": "star wars yoda",
                                "thanos perfectly balanced as all things should be": "thanos perfectly balanced",
                                "thanos perfectly balanced": "thanos perfectly balanced",
                                "crack": "yall got any more of",
                                "crack head": "yall got any more of",
                                "tyrone biggums the addict": "yall got any more of",
                                "dave chappelle yall got any more of crackhead": "yall got any more of",
                                "yall got any more of them": "yall got any more of",
                                "dave chappelle": "yall got any more of",
                                "yall got any more of that": "yall got any more of",
                                "yall got any more of": "yall got any more of",
                                "crying cat": "crying cat",
                                "oh yeah! oh no": "disappointed black guy",
                                "black guy happy sad": "disappointed black guy",
                                "disappointed black guy": "disappointed black guy",
                                "peter parker cry": "crying peter parker",
                                "crying peter parker": "crying peter parker",
                                "burning house girl": "disaster girl",
                                "disaster girl": "disaster girl",
                                "distracted boyfriend": "distracted boyfriend",
                                "wait thats illegal": "wait thats illegal",
                                "ralph in danger": "chuckles im in danger",
                                "im in danger + blank place above": "chuckles im in danger",
                                "chuckles im in danger": "chuckles im in danger",
                                "archer": "do you want ants archer",
                                "do you want ants archer": "do you want ants archer",
                                "virgin and chad": "virgin vs chad",
                                "virgin vs chad": "virgin vs chad",
                                "doge 2": "doge",
                                "doge": "doge",
                                "make america great again": "donald trump",
                                "trump bill signing": "donald trump",
                                "trump lawn mower": "donald trump",
                                "donal trump birthday": "donald trump",
                                "donald trump approves": "donald trump",
                                "donald trump birthday": "donald trump",
                                "donald trump": "donald trump",
                                "dr evil air quotes": "dr evil",
                                "dr evil laser": "dr evil",
                                "dr evil pinky": "dr evil",
                                "dr evil quotes": "dr evil",
                                "dr evil": "dr evil",
                                "dwight schrute 2": "dwight schrute",
                                "dwight schrute": "dwight schrute",
                                "black white arms": "epic handshake",
                                "predator handshake": "epic handshake",
                                "epic handshake": "epic handshake",
                                "galaxy brain 3 brains": "expanding brain",
                                "expanding brain 3 panels": "expanding brain",
                                "expanding brain 5 panel": "expanding brain",
                                "expanding brain": "expanding brain",
                                "fancy winnie the pooh meme": "fancy pooh",
                                "tuxedo winnie the pooh 3 panel": "fancy pooh",
                                "tuxedo winnie the pooh 4 panel": "fancy pooh",
                                "tuxedo winnie the pooh": "fancy pooh",
                                "bestbetter blurst": "fancy pooh",
                                "fancy pooh": "fancy pooh",
                                "black scientist finally xium": "finally",
                                "finally": "finally",
                                "for dummies book": "for dummies",
                                "for dummies": "for dummies",
                                "forever alone christmas": "forever alone",
                                "forever alone happy": "forever alone",
                                "forever alone": "forever alone",
                                "blue futurama fry": "futurama fry",
                                "not sure if- fry": "futurama fry",
                                "futurama fry": "futurama fry",
                                "gangnam style psy": "gangnam style",
                                "psy horse dance": "gangnam style",
                                "gangnam style2": "gangnam style",
                                "gangnam style": "gangnam style",
                                "gru diabolical plan fail": "grus plan",
                                "grus plan": "grus plan",
                                "aj styles & undertaker": "undertaker",
                                "randy orton undertaker": "undertaker",
                                "undertaker": "undertaker",
                                "zombie bad luck brian": "bad luck brian",
                                "bad luck brian": "bad luck brian",
                                "grumpy cats father": "grumpy cat",
                                "grumpy cat bed": "grumpy cat",
                                "grumpy cat birthday": "grumpy cat",
                                "grumpy cat christmas": "grumpy cat",
                                "grumpy cat does not believe": "grumpy cat",
                                "grumpy cat halloween": "grumpy cat",
                                "grumpy cat happy": "grumpy cat",
                                "grumpy cat mistletoe": "grumpy cat",
                                "grumpy cat not amused": "grumpy cat",
                                "grumpy cat reverse": "grumpy cat",
                                "grumpy cat sky": "grumpy cat",
                                "grumpy cat star wars": "grumpy cat",
                                "grumpy cat table": "grumpy cat",
                                "grumpy cat top hat": "grumpy cat",
                                "grumpy cat": "grumpy cat",
                                "homer simpson in bush - large": "homer disappears into bush",
                                "homer bush": "homer disappears into bush",
                                "homer disappears into bush": "homer disappears into bush",
                                "here we go again": "ah shit here we go again",
                                "ah shit here we go again": "ah shit here we go again",
                                "hes probably thinking about girls": "i bet hes thinking about other women",
                                "thinking of other girls": "i bet hes thinking about other women",
                                "i bet hes thinking about other women": "i bet hes thinking about other women",
                                "joe biden 2020": "joe biden",
                                "sad joe biden": "joe biden",
                                "joe biden worries": "joe biden",
                                "joe biden": "joe biden",
                                "krusty krab vs chum bucket blank": "krusty krab vs chum bucket",
                                "krusty krab vs chum bucket": "krusty krab vs chum bucket",
                                "leonardo dicaprio django laugh": "laughing leo",
                                "laughing leo": "laughing leo",
                                "madea": "madea with gun",
                                "madea with gun": "madea with gun",
                                "marvel civil war 1": "marvel civil war",
                                "marvel civil war 2": "marvel civil war",
                                "marvel civil war": "marvel civil war",
                                "side eye teddy": "monkey looking away",
                                "monkey puppet": "monkey looking away",
                                "monkey looking away": "monkey looking away",
                                "hold fart": "straining kid",
                                "when you havent told anybody": "straining kid",
                                "neck vein guy": "straining kid",
                                "straining kid": "straining kid",
                                "nick young": "black guy confused",
                                "black guy confused": "black guy confused",
                                "npc meme": "npc",
                                "npc": "npc",
                                "phoebe teaching joey in friends": "phoebe joey",
                                "phoebe joey": "phoebe joey",
                                "persian cat room guardian single": "persian cat room guardian",
                                "persian cat room guardian": "persian cat room guardian",
                                "rick and carl 3": "rick and carl",
                                "rick and carl long": "rick and carl",
                                "rick and carl longer": "rick and carl",
                                "rick and carl": "rick and carl",
                                "samuel jackson glance": "samuel l jackson",
                                "samuel l jackson": "samuel l jackson",
                                "spider man double": "spiderman",
                                "spider man triple": "spiderman",
                                "spiderman camera": "spiderman",
                                "spiderman computer desk": "spiderman",
                                "spiderman hospital": "spiderman",
                                "spiderman mirror": "spiderman",
                                "spiderman pointing at spiderman": "spiderman",
                                "spiderman presentation": "spiderman",
                                "sexy railroad spiderman": "spiderman",
                                "spiderman": "spiderman",
                                "dog on fire": "this is fine",
                                "this is fine": "this is fine",
                                "what do we want 3": "x all the y",
                                "what do we want": "x all the y",
                                "x all the y": "x all the y",
                                "sponge finna commit muder": "spongebob strong",
                                "spongebob strong": "spongebob strong",
                                "spongebob stupid": "mocking spongebob",
                                "mocking spongebob": "mocking spongebob",
                                "soldier protecting sleeping child": "the silent protector",
                                "the silent protector": "the silent protector",
                                "spongebob rainbow": "imagination spongebob",
                                "imagination spongebob": "imagination spongebob",
                                "empty stonks": "stonks",
                                "stonks without stonks": "stonks",
                                "stonks": "stonks",
                                "the office congratulations": "the office handshake",
                                "the office handshake": "the office handshake",
                                "this is fine blank": "this is fine",
                                "timmys turner dad": "this is where id put my trophy if i had one",
                                "this is where id put my trophy if i had one": "this is where id put my trophy if i had one",
                                "triggered liberal": "triggered feminist",
                                "triggered feminist": "triggered feminist",
                                "vince mcmahon reaction wglowing eyes": "vince mcmahon",
                                "mr mcmahon reaction": "vince mcmahon",
                                "vince mcmahon reaction": "vince mcmahon",
                                "mcmahon": "vince mcmahon",
                                "vince mcmahon": "vince mcmahon",
                                "waiting skeleton": "skeleton waiting",
                                "skeleton waiting": "skeleton waiting",
                                "we dont do that here": "we dont do that here",
                                "captain phillips - im the captain now": "look at me",
                                "im the captain now": "look at me",
                                "look at me": "look at me",
                                "oprah you get a car everybody gets a car": "oprah you get a",
                                "oprah you get a": "oprah you get a",
                                "drowning kid in the pool": "mother ignoring kid drowning in a pool",
                                "mother ignoring kid drowning in a pool": "mother ignoring kid drowning in a pool",
                                "oh no anyway": "oh no! anyway",
                                "oh no! anyway": "oh no! anyway",
                                "licking lips": "anthony adams rubbing hands",
                                "black guy hiding behind tree": "anthony adams rubbing hands",
                                "anthony adams rubbing hands": "anthony adams rubbing hands",
                                "alien meeting suggestion": "boardroom meeting suggestion",
                                "emergency meeting among us": "boardroom meeting suggestion",
                                "among us meeting": "boardroom meeting suggestion",
                                "boardroom meeting suggestion": "boardroom meeting suggestion",
                                "matrix morpheus": "what if i told you",
                                "what if i told you": "what if i told you",
                                "party loner": "they dont know",
                                "they dont know": "they dont know"}

ALT_NAMES = set(REPLICATED_TEMPLATES_GROUPED.keys())-set(REPLICATED_TEMPLATES_GROUPED.values())
