version: "3.7"
services:
  celery:
    image: distortedlogic/python:${IMAGE_TAG}
    build: .
    container_name: celery
    restart: on-failure
    command: doppler run -- celery -A src.celery.CELERY worker -B -l info
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_PYTHON}
    volumes:
      - .:/app/
  celery-monitor:
    image: distortedlogic/flower:${IMAGE_TAG}
    build:
      context: .
    container_name: flower-${IMAGE_TAG}
    command: doppler run -- celery -A src.celery.CELERY flower
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_PYTHON}
    restart: on-failure
    volumes:
      - .:/app/
    ports:
      - 5555:5555
    logging:
      driver: none
    depends_on:
      - celery
