"""init

Revision ID: 3bc6348d0568
Revises: 
Create Date: 2022-06-28 18:52:37.001459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bc6348d0568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('is_test_set', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('not_meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('is_test_set', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('not_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('is_test_set', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(length=400), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=True),
    sa.Column('reddit_meme_id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.String(length=400), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('not_meme', sa.Boolean(), nullable=False),
    sa.Column('not_template', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation')
    op.drop_table('not_template')
    op.drop_table('not_meme')
    op.drop_table('meme_template')
    # ### end Alembic commands ###
