"""created_at_validation

Revision ID: 6f682c6bac0b
Revises: 3bc6348d0568
Create Date: 2022-07-03 11:31:45.821917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f682c6bac0b'
down_revision = '3bc6348d0568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation', 'created_at')
    # ### end Alembic commands ###
