on:
  push:
    branches:
      - dev

name: Deploy to development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        env:
          REGISTRY: memehub
          REPOSITORY: python
          IMAGE_TAG: dev
          DOPPLER_TOKEN: ${{ secrets.DEV_DOPPLER_TOKEN }}
        run: |
          docker build --build-arg DOPPLER_TOKEN=$DOPPLER_TOKEN -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile.prod .
      - name: Push Docker Image
        env:
          REGISTRY: memehub
          REPOSITORY: python
          IMAGE_TAG: dev
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
